image: golang
git:
  path: github.com/gouyang/goblog
script:
    - go get github.com/abbot/go-http-auth
    - go get github.com/russross/blackfriday
    - go get github.com/mattn/go-sqlite3
    - go get github.com/russross/blackfriday
    - go get github.com/gorilla/mux
    - go get github.com/shurcooL/sanitized_anchor_name
    - go get github.com/goji/httpauth
    - go build .
notify:
  email:
    recipients:
      - gouyang@redhat.com
