language: go
go:
  - 1.3
install:
  - go get github.com/abbot/go-http-auth
  - go get github.com/russross/blackfriday
  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
  - go get github.com/gorilla/mux
script:
  - go build .
