language: go
go:
  - 1.3
install:
  - go get github.com/abbot/go-http-auth
  - go get github.com/russross/blackfriday
  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
  - go get github.com/gorilla/mux
  - go get github.com/nabeken/negroni-auth
  - go get github.com/codegangsta/negroni
  - go get github.com/goji/httpauth
script:
  - go build .
